### ISSUE TITLE
intendation "rules" unclear

### ISSUE THREAD

**Issue by MiniXC** [nopr/sassdown#76]
I recently tried to get sassdown running, and was wondering why the iframe wasn't created.
For example, it failed with
```scss
/*

Alerts
======

Creates an alert box notification using the `.alert-` prefix. The following options are available:

  <p class="alert-success">Winning</p>
  <p class="alert-warning">Steady</p>
  <p class="alert-error">Oh Shit!</p>

*/

@mixin alert($colour){
  color: darken($colour, 50%);
  background: $colour;
  border-radius: 5px;
  margin-bottom: 1.2em;
  padding: 1em;
}

.alert-success { @include alert(#e2f3c1) }
.alert-warning { @include alert(#fceabe) }
.alert-error   { @include alert(#ffdcdc) }
```
The code seemed perfectly valid to me, but I found that when using only one `tab` for intendation, the markup snipped wasn't recognized. Only after adding a second one, sassdown did its magic ;)

Maybe you could add this to the documentation? Or even allow a single tab for intendation?
